### ISSUE TITLE
Multipolygon

### ISSUE THREAD

**Issue by dotevo** [yarl/osmtools-indoor#7]
http://osmtools.org/indoor/#lat=51.23569&lon=22.71491&z=21 
Tutaj jest ściana, która się nie wyświetla ponieważ corridor nie ma konturów. Rozwiązaniem jest możliwość stosowania multipolygonów dla buildingpart.

**Comment by yarl** [comment]
Dodałem kontury dla korytarzy, wygląda całkiem nieźle
